---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ministral-model-pvc
  namespace: llm
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      # if we're using K3s, default storage class is local-path
      storage: 30Gi