apiVersion: v1
kind: Namespace
metadata:
  name: nvidia-device-plugin
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: nvidia-device-plugin
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nvidia-device-plugin-ds
    spec:
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      priorityClassName: system-node-critical
      containers:
      - image: nvcr.io/nvidia/k8s-device-plugin:v0.17.4
        name: nvidia-device-plugin-ctr
        args:
        - "--fail-on-init-error=false"
        - "--pass-device-specs=true"
        env:
        - name: CONTAINERD_SOCKET
          value: "/run/k3s/containerd/containerd.sock"
        - name: RUNTIME
          value: "containerd"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: CDI_ROOT
          value: "/etc/cdi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: containerd-sock
          mountPath: /run/k3s/containerd/containerd.sock
        - name: dev
          mountPath: /dev
        - name: cdi
          mountPath: /etc/cdi
          readOnly: true
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: containerd-sock
        hostPath:
          path: /run/k3s/containerd/containerd.sock
          type: Socket
      - name: dev
        hostPath:
          path: /dev
          type: Directory
      - name: cdi
        hostPath:
          path: /etc/cdi
          type: DirectoryOrCreate
      # nodeSelector:
      #   accelerator: nvidia

